function [fitresult, gof] = createFit(times, T1111)
%CREATEFIT(TIMES,T1111)
%  Create a fit.
%
%  Data for 'Fit1' fit:
%      X Input : times
%      Y Output: T1111
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Sep-2014 10:54:13


%% Fit: 'Fit1'.
[xData, yData] = prepareCurveData( times, T1111 );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.Robust = 'LAR';
opts.StartPoint = [0.1526 0.977534204322301 0.345189565874671];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit1' );
h = plot( fitresult, xData, yData );
legend( h, 'T1111 vs. times', 'Fit1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'times' );
ylabel( 'T1111' );
grid on


